.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SKANLITE 1 "30. Mai 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
Skanlite \- KDE-4-Programm, basierend auf KSane, zum Einscannen von Bildern
.SH SYNTAX
.B skanlite
.RI [ -d <Gerät> ]
.SH BESCHREIBUNG
Diese Anleitung dokumentiert den Befehl
.B Skanlite
in groben Zügen.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBSkanlite\fP ist ein Programm zum Einscannen von Bildern. Die Bedienung
erfolgt mittels einer grafischen Oberfläche (GUI).
.SH OPTIONEN
Es folgt eine Zusammenfassung der Optionen, um alle Optionen angezeigt zu
bekommen, rufen Sie bitte
.B skanlite --help-all
auf.
.TP
.B \-d <Gerät>
Den Namen - wie er von SANE ausgegeben wird - des zu verwendenden Gerätes an
Skanlite übergeben.
.TP
.B \-\-help
Eine kurze Zusammenfassug der wichtigsten Optionen anzeigen lassen.
.TP
.B \-\-help\-all
Alle Optionen anzeigen.
.TP
.B \-v, \-\-version
Programmversion ausgeben.
.SH SIEHE AUCH
.BR sane-find-scanner (1),
.BR
.BR
Das Programm ist vollständig in der über das KHelpCenter verfügbaren Hilfe 
dokumentiert.
.SH AUTOREN
Skanlite wurde von Kåre Särs <kare.sars@iki.fi> und
Arseniy Lartsev <receive-spam@yandex.ru> geschrieben.
.PP
Diese Hilfe-Seite ist von Kai Wasserbäch <debian@carbon-project.org> 
für das Debian-Projekt geschrieben worden und darf von Anderen verwandt werden.
